{
  "asyncapi" : "2.0.0",
  "id" : "urn:zbos-mqtt-api",
  "defaultContentType" : "application/json",
  "info" : {
    "title" : "Face tracking",
    "version" : "2.7.1",
    "description" : "API for communication with ZBOS by Zora Robotics.",
    "contact" : {
      "email" : "info@zorarobotics.be"
    }
  },
  "channels" : {
    "zbos/facetracking/start" : {
      "publish" : {
        "summary" : "Start continuous facetracking, see <<zbos/facetracking/detected/faces>> for events",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/emptyMessage"
        }
      }
    },
    "zbos/facetracking/stop" : {
      "publish" : {
        "summary" : "Stop continuous facetracking",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/emptyMessage"
        }
      }
    },
    "zbos/facetracking/detected/faces" : {
      "subscribe" : {
        "summary" : "event: Detected faces",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "uuid" : {
                  "type" : "string"
                },
                "name" : {
                  "type" : "string"
                },
                "role" : {
                  "type" : "string"
                }
              }
            }
          },
          "name" : "Array<Person>",
          "examples" : [ {
            "payload" : {
              "uuid" : "some uuid",
              "name" : "some name",
              "role" : "some description"
            }
          }, {
            "payload" : {
              "name" : "unknown"
            }
          } ]
        }
      }
    },
    "zbos/camera/picture/event" : {
      "publish" : {
        "summary" : "event: Get picture",
        "description" : "Picture in base64 formatsee zbos/facetracking/response for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "string"
          },
          "name" : "String"
        }
      }
    },
    "zbos/facetracking/response" : {
      "subscribe" : {
        "summary" : "response: Face",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "uuid" : {
                  "type" : "string"
                },
                "name" : {
                  "type" : "string"
                },
                "role" : {
                  "type" : "string"
                }
              }
            }
          },
          "name" : "Array<Person>",
          "examples" : [ {
            "payload" : {
              "uuid" : "some uuid",
              "name" : "some name",
              "role" : "some description"
            }
          }, {
            "payload" : {
              "name" : "unknown"
            }
          } ]
        }
      }
    },
    "zbos/facetracking/add_request" : {
      "publish" : {
        "summary" : "Add a person",
        "description" : "see <<zbos/facetracking/add_response>> for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "object",
            "properties" : {
              "name" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string",
                "description" : "Optional, a descriptor for this person"
              },
              "ImageString" : {
                "type" : "string",
                "description" : "Optional, if this has a value (in base64) the given image will be used. Otherwise, a stream will be started to find a new person"
              },
              "options" : {
                "type" : "object",
                "description" : "Optional, the global options will be used if no value is given",
                "properties" : {
                  "mode" : {
                    "type" : "string",
                    "description" : "How closely the person must match",
                    "enum" : [ "LOOSE", "NORMAL", "STRICT" ]
                  },
                  "tries" : {
                    "type" : "integer",
                    "description" : "How many times to check for a person before giving up"
                  },
                  "timeout" : {
                    "type" : "integer",
                    "description" : "How long to look for a person before giving up"
                  }
                }
              }
            }
          },
          "name" : "PersonAddRequest",
          "examples" : [ {
            "payload" : {
              "name" : "some name",
              "role" : "some description"
            }
          }, {
            "payload" : {
              "name" : "another name",
              "options" : {
                "mode" : "STRICT",
                "tries" : 5,
                "timeout" : 60
              },
              "role" : "another description",
              "ImageString" : "some base64 image"
            }
          } ]
        }
      }
    },
    "zbos/facetracking/add_response" : {
      "subscribe" : {
        "summary" : "response: Add a person",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/successMessage"
        }
      }
    },
    "zbos/facetracking/update_request" : {
      "publish" : {
        "summary" : "Add a new face to an existing person",
        "description" : "see <<zbos/facetracking/update_response>> for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/emptyMessage"
        }
      }
    },
    "zbos/facetracking/update_response" : {
      "subscribe" : {
        "summary" : "response: Add a new face to an existing person",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/successMessage"
        }
      }
    },
    "zbos/facetracking/update_person_request" : {
      "publish" : {
        "summary" : "Update a person",
        "description" : "see <<zbos/facetracking/update_person_response>> for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "object",
            "properties" : {
              "uuid" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string"
              }
            }
          },
          "name" : "Person",
          "examples" : [ {
            "payload" : {
              "uuid" : "some uuid",
              "name" : "some new name",
              "role" : "some new description"
            }
          } ]
        }
      }
    },
    "zbos/facetracking/update_person_response" : {
      "subscribe" : {
        "summary" : "response: Update a person",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/successMessage"
        }
      }
    },
    "zbos/facetracking/delete_request" : {
      "publish" : {
        "summary" : "Delete a person",
        "description" : "see <<zbos/facetracking/delete_response>> for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "object",
            "properties" : {
              "uuid" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string"
              }
            }
          },
          "name" : "Person",
          "examples" : [ {
            "payload" : {
              "uuid" : "some uuid"
            }
          } ]
        }
      }
    },
    "zbos/facetracking/delete_response" : {
      "subscribe" : {
        "summary" : "response: Delete a person",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/successMessage"
        }
      }
    },
    "zbos/facetracking/name_request" : {
      "publish" : {
        "summary" : "Request the list of registered persons",
        "description" : "see <<zbos/facetracking/name_response>> for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "$ref" : "#/components/messages/emptyMessage"
        }
      }
    },
    "zbos/facetracking/name_response" : {
      "subscribe" : {
        "summary" : "response: Request the list of registered persons",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "uuid" : {
                  "type" : "string"
                },
                "name" : {
                  "type" : "string"
                },
                "role" : {
                  "type" : "string"
                }
              }
            }
          },
          "name" : "Array<Person>"
        }
      }
    },
    "zbos/facetracking/persondata_request" : {
      "publish" : {
        "summary" : "Request all data of a person",
        "description" : "see <<zbos/facetracking/persondata_response>> for response\n",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "object",
            "properties" : {
              "uuid" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string"
              }
            }
          },
          "name" : "Person",
          "examples" : [ {
            "payload" : {
              "uuid" : "some uuid"
            }
          } ]
        }
      }
    },
    "zbos/facetracking/persondata_response" : {
      "subscribe" : {
        "summary" : "response: Request all data of a person",
        "description" : "",
        "tags" : [ {
          "name" : "Face tracking",
          "description" : "All face tracking related topics."
        } ],
        "message" : {
          "payload" : {
            "type" : "object",
            "properties" : {
              "uuid" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string"
              },
              "image" : {
                "type" : "string",
                "description" : "A base64 image of this person"
              }
            }
          },
          "name" : "PersonGetResponse",
          "examples" : [ {
            "payload" : {
              "uuid" : "some uuid",
              "name" : "some name",
              "image" : "some base64 image",
              "role" : "some description"
            }
          } ]
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "percentage" : {
        "type" : "integer",
        "maximum" : 100,
        "minimum" : 0,
        "description" : "Percentage value between with range 0 to 100"
      },
      "key" : {
        "type" : "string",
        "description" : "Required random key"
      }
    },
    "messages" : {
      "emptyMessage" : {
        "payload" : {
          "type" : "object"
        },
        "name" : "EmptyMessage",
        "summary" : "Empty message"
      },
      "keyMessage" : {
        "payload" : {
          "type" : "object",
          "properties" : {
            "key" : {
              "type" : "string",
              "description" : "Required random key"
            }
          }
        },
        "name" : "KeyResult",
        "summary" : "Random key",
        "examples" : [ {
          "payload" : {
            "key" : "ABCxyz"
          }
        } ]
      },
      "successMessage" : {
        "payload" : {
          "type" : "object",
          "properties" : {
            "success" : {
              "type" : "boolean"
            },
            "message" : {
              "type" : "string",
              "description" : "Optional error message"
            }
          }
        },
        "name" : "SuccessMessage",
        "summary" : "Success message",
        "examples" : [ {
          "payload" : {
            "success" : true
          }
        } ]
      },
      "notificationMessage" : {
        "payload" : {
          "type" : "object",
          "properties" : {
            "message" : {
              "type" : "object",
              "properties" : {
                "message" : {
                  "type" : "string"
                },
                "translate" : {
                  "type" : "boolean"
                },
                "formatArguments" : {
                  "type" : "array",
                  "items" : {
                    "type" : "string"
                  }
                },
                "translationCategory" : {
                  "type" : "string"
                }
              }
            }
          }
        },
        "name" : "NotificationOptions",
        "summary" : "Message json",
        "examples" : [ {
          "payload" : {
            "message" : {
              "message" : "string",
              "translate" : true,
              "formatArguments" : [ "string" ]
            }
          }
        } ]
      }
    }
  },
  "tags" : [ {
    "name" : "Speech",
    "description" : "All speech related topics."
  }, {
    "name" : "Motion",
    "description" : "All motion related topics."
  }, {
    "name" : "Audio",
    "description" : "All audio related topics."
  }, {
    "name" : "Status",
    "description" : "All status related topics."
  }, {
    "name" : "System",
    "description" : "All system related topics."
  }, {
    "name" : "Sensors",
    "description" : "All sensors related topics."
  }, {
    "name" : "Leds",
    "description" : "All leds related topics."
  }, {
    "name" : "Composer",
    "description" : "All composer related topics."
  }, {
    "name" : "Kiosk",
    "description" : "All kiosk related topics."
  }, {
    "name" : "Media",
    "description" : "All media related topics."
  }, {
    "name" : "Applications",
    "description" : "All applications related topics."
  }, {
    "name" : "Translations",
    "description" : "All translations related topics."
  }, {
    "name" : "Settings",
    "description" : "All settings related topics."
  }, {
    "name" : "Camera",
    "description" : "All camera related topics."
  }, {
    "name" : "Domotics",
    "description" : "All domotics related topics."
  }, {
    "name" : "Cloud",
    "description" : "All cloud related topics."
  }, {
    "name" : "SLAM",
    "description" : "All slam related topics."
  }, {
    "name" : "Wifi",
    "description" : "All wifi related topics."
  }, {
    "name" : "Connection",
    "description" : "All connection related topics."
  }, {
    "name" : "Survey",
    "description" : "All survey related topics."
  }, {
    "name" : "Motion detection",
    "description" : "All motion detection related topics."
  }, {
    "name" : "Face tracking",
    "description" : "All face tracking related topics."
  }, {
    "name" : "SIP",
    "description" : "All sip related topics."
  }, {
    "name" : "Time",
    "description" : "All time related topics."
  }, {
    "name" : "Variables",
    "description" : "All variables related topics."
  }, {
    "name" : "Diagnostics",
    "description" : "All diagnostics related topics."
  } ]
}